# Generated by Django 5.2.9 on 2025-12-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region_sido', models.CharField(max_length=50)),
                ('region_sigungu', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('naver_place_id', models.CharField(blank=True, max_length=100)),
                ('google_place_id', models.CharField(blank=True, max_length=100)),
                ('avg_rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('summary_positive', models.TextField(blank=True)),
                ('summary_negative', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='vendors.vendorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserVendorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', '후보'), ('final', '최종 선택')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_selections', to='weddings.weddingprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'unique_together': {('profile', 'vendor')},
            },
        ),
    ]
