# Generated by Django 6.0 on 2026-02-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcategory',
            options={'verbose_name_plural': 'Vendor Categories'},
        ),
    ]
