# Generated by Django 5.2.9 on 2025-12-02 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_date', models.DateField()),
                ('region_sido', models.CharField(max_length=50)),
                ('region_sigungu', models.CharField(blank=True, max_length=50)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('d_day_offset', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='weddings.weddingprofile')),
            ],
        ),
    ]
