# Generated by Django 5.2.9 on 2025-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='estimated_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
