# Generated by Django 5.2.9 on 2025-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='category',
            field=models.CharField(choices=[('MEETING', '상견례'), ('VENUE', '예식장'), ('SDM', '스드메'), ('ATTIRE', '예복/한복'), ('INVITATION', '청첩장'), ('HONEYMOON', '신혼여행'), ('FURNISHING', '혼수'), ('CONTRACT', '계약/결제'), ('OTHER', '기타')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='d_day_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
