# Generated by Django 6.0 on 2025-12-30 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_post_comment_delete_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='recommended_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
