# Generated by Django 6.0 on 2026-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0005_remove_weddingprofile_wedding_date_noticecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CHAT', '수다'), ('QUESTION', '질문'), ('REVIEW', '후기'), ('TIP', '꿀팁')], default='CHAT', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
